version: '3'

services:

  # Apache 2.4
  web:
    build: .
    container_name: web
    environment:
      XDEBUG_CONFIG: "remote_host=172.17.0.1"
      PHP_IDE_CONFIG: "serverName=<Your debug Server name inside PHPStorm>"
    ports:
      - "8001:80"
      - "8002:22"
      - "8003:443"
    links:
      - db
    volumes:
      - ./app:/var/www/app

  # MariaDB 10.4
  db:
    image: "mariadb:10.4"
    container_name: db
    ports:
      - 8306:3306
    volumes:
      - ./mysql/data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: TzDbR6hiYEGxzoOvVycg
      MYSQL_DATABASE: app_database
      MYSQL_USER: app_user
      MYSQL_PASSWORD: GEAuqLFIqpqrN5yGOowZ
