version: '3'

services:
  # Apache 2.4
  apache:
    build: './apache/'
    container_name: apache
    ports:
      - "80:80"
      - "443:443"
    depends_on:
      - mariadb
      - php
    networks:
      - main
    volumes:
      - ./app:/var/www/html

  # PHP 7.4 FPM
  php:
    build: './php/'
    container_name: php
    #environment:
    #  XDEBUG_CONFIG: "remote_host=172.17.0.1"
    #  PHP_IDE_CONFIG: "serverName=<Your debug Server name inside PHPStorm>"
    networks:
      - main
    volumes:
      - ./app:/var/www/html

  node:
    build: './node/'
    container_name: node
    networks:
      - main
    volumes:
      - ./app:/home/node/app
    tty: true

  # MariaDB 10.4
  mariadb:
    image: "mariadb:10.4"
    container_name: mariadb
    ports:
      - 3306:3306
    volumes:
      - ./mysql/data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: TzDbR6hiYEGxzoOvVycg
      MYSQL_DATABASE: app_database
      MYSQL_USER: app_user
      MYSQL_PASSWORD: GEAuqLFIqpqrN5yGOowZ
    networks:
      - main


networks:
  main:
