version: '2'

services:
  web:
    build: .
    container_name: web
    ports:
      - "8001:80"
      - "8002:22"
      - "8003:443"
    links:
      - db
    volumes:
      - ./app:/var/www/app
    command: /usr/sbin/apache2ctl -DFOREGROUND

  db:
    image: "mysql:5.5"
    container_name: db
    ports:
      - 8306:3306
    volumes:
      - ./mysql:/etc/mysql/conf.d
    environment:
      MYSQL_ROOT_PASSWORD: root_password
      MYSQL_DATABASE: db_name
      MYSQL_USER: db_user
      MYSQL_PASSWORD: db_user_password
