version: '3'

services:
  # Apache 2.4
  apache:
    build: './apache/'
    container_name: appname-apache
    ports:
      - "8080:80"
      - "8443:443"
    depends_on:
      - mariadb
      - php
    networks:
      - main
    volumes:
      - ./app:/var/www/html
      - ./apache/ssl:/etc/apache2/ssl

  # PHP 7.4 FPM
  php:
    build: './php/'
    container_name: appname-php
    #environment:
    #  XDEBUG_CONFIG: "remote_host=172.17.0.1"
    #  PHP_IDE_CONFIG: "serverName=localhost"
    networks:
      - main
    volumes:
      - ./app:/var/www/html

  # Node.js
  node:
    build: './node/'
    container_name: appname-node
    networks:
      - main
    volumes:
      - ./app:/home/node/app
    tty: true

  # MariaDB 10.5
  mariadb:
    image: "mariadb:10.5"
    container_name: appname-mariadb
    ports:
      - 33306:3306
    volumes:
      - ./mariadb/data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: TzDbR6hiYEGxzoOvVycg
      MYSQL_DATABASE: app_database
      MYSQL_USER: app_user
      MYSQL_PASSWORD: GEAuqLFIqpqrN5yGOowZ
    networks:
      - main

networks:
  main:
