version: '3'

services:
  # PHP 7.4, Apache
  apache-php:
    build: './php/'
    container_name: apache-php
    environment:
      XDEBUG_CONFIG: "remote_host=172.17.0.1"
      PHP_IDE_CONFIG: "serverName=<Your debug Server name inside PHPStorm>"
    ports:
      - "80:80"
      - "443:443"
    depends_on:
      - mariadb
    networks:
      - main
    volumes:
      - ./app:/var/www/html
      - ./vhosts:/etc/apache2/sites-enabled
      - ./php/ini:/usr/local/etc/php

  # MariaDB 10.4
  mariadb:
    image: "mariadb:10.4"
    container_name: mariadb
    ports:
      - 3306:3306
    volumes:
      - ./mysql/data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: TzDbR6hiYEGxzoOvVycg
      MYSQL_DATABASE: app_database
      MYSQL_USER: app_user
      MYSQL_PASSWORD: GEAuqLFIqpqrN5yGOowZ
    networks:
      - main

networks:
  main:
